services:
    proxy:
        image: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        ports:
            - 80:80
        depends_on:
            - python_backend
            - react_frontend
        networks:
            - backnet

    python_backend:
        container_name: python_backend
        build:
            context: ./backend
            target: dev-envs
        stop_signal: SIGINT
        ports:
            - 8000:8000
        volumes:
            - ./backend:/code
        depends_on:
            - db
        networks:
            - backnet

    react_frontend:
        container_name: react_frontend
        build:
            context: ./frontend
        ports:
            - 3000:80
        volumes:
            - ./frontend:/code
            - /code/node_modules
        networks:
            - backnet
        depends_on:
            - python_backend
        expose:
            - 3306
            - 33060

    db:
        container_name: db
        image: mysql
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tres_con_todo
        ports:
            - 3306:3306
        networks:
            - backnet

networks:
    backnet:

volumes:
    db-data:
