services:
    proxy:
        image: nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf:ro
            - ./certbot/www:/var/www/certbot/:ro
            - ./certbot/conf/:/etc/nginx/ssl/:ro
        ports:
            - 80:80
            - 443:443
        depends_on:
            - python_backend
            - react_frontend
        networks:
            - backnet

    certbot:
        image: certbot/certbot:latest
        volumes:
          - ./certbot/www/:/var/www/certbot/:rw
          - ./certbot/conf/:/etc/letsencrypt/:rw

    python_backend:
        container_name: python_backend
        build:
            context: ./backend
            target: dev-envs
        stop_signal: SIGINT
        ports:
            - 8000:8000
        volumes:
            - ./backend:/code
        depends_on:
            - db
        networks:
            - backnet

    react_frontend:
        container_name: react_frontend
        build:
            context: ./frontend
            target: development
        ports:
            - 3000:3000
        volumes:
            - ./frontend:/code
            - /code/node_modules
        networks:
            - backnet
        depends_on:
            - python_backend
        expose:
            - 3306
            - 33060

    db:
        container_name: db
        image: mysql
        volumes:
            - db-data:/var/lib/mysql
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: tres_con_todo
        ports:
            - 3306:3306
        networks:
            - backnet

networks:
    backnet:

volumes:
    db-data:
