name: Frontend App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./frontend

    steps:
    - uses: actions/checkout@v3
    - name: Use Node 20.11.1
      uses: actions/setup-node@v3
      with:
        node-version: 20.11.1
    - name: Installing dependencies
      run: npm ci
    - name: Building
      run: npm run build --if-present
    - name: Testing
      run: npm test
